# -*- coding: utf-8 -*-
"""correlation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnNmsO82VLIcqiesQgyhyk4fp8aiakQg
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
#corelation of person getting good marks
np.random.seed(42)
data = {
    "Study Hours": np.random.randint(1,10,50),
    "Marks": np.random.randint(90,100,50),
    "Screen Time": np.random.randint(1,7,50),
    "Traveling Time":np.random.randint(1,10,50),
    "Sleep Hours":np.random.randint(1,10,50),
}
df=pd.DataFrame(data)

#compute correlation matrix
corr = df.corr()

#plot heatmap
# sns.heatmap(corr,annot=True,cmap="coolwarm")
plt.figure(figsize=(8,6))
sns.heatmap(corr,annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5, linecolor="gray")
plt.title("Correlation Heatmap")
plt.show()

import pandas as pd

# Step 2: Upload the CSV file

from google.colab import files

uploaded = files.upload()

# Step 3: Read the uploaded CSV file

# Replace 'your_file.csv' with the actual file name after upload

file_name = list(uploaded.keys())[0]  # Automatically gets the uploaded file name

df = pd.read_csv("car_price_dataset")
print(df)