# -*- coding: utf-8 -*-
"""Data_cleaning_imputations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URFIDikp8DNJwpTJWaTXiWnrESd1sIXf
"""

import pandas as pd

import numpy as np

# Create sample dataset (House Price Dataset with missing values)

data = {

    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],  # Numeric

    'Year_built': [2003, 1976, 2001, np.nan, 1998, 2000, 2006, 1978, 1950, np.nan],             # Numeric

    'over_all_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],                            # Numeric

    'ready_to_move': ['Yes', 'No', 'NO', np.nan, 'No', np.nan, 'No', 'Yes', 'No', 'Yes'],     # Categorical (Yes/No)

    'Sale_price': [200000, 180000, 215000, 250000, 210000, 190000, 230000, 225000, 220000, 240000]  # Target Variable (Numeric)

}
df=pd.DataFrame(data)
print("original DataFrame")
print(df)

#filling the missing values
df['square_feet_area'].fillna(df['square_feet_area'].mean(),inplace=True)
df['Year_built'].fillna(df['Year_built'].mean(),inplace=True)
df['over_all_condition'].fillna(df['over_all_condition'].mean(),inplace=True)

#replacing missing values with the mode for categorical columns
df['ready_to_move'].fillna(df['ready_to_move'].mode()[0],inplace=True) #moce for ready_to_move

#print dataframe after imputation
print("DataFrame after imputation")
print(df)

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
data = {

    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],  # Numeric

    'Year_built': [2003, 1976, 2001, np.nan, 1998, 2000, 2006, 1978, 1950, np.nan],             # Numeric

    'over_all_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],                            # Numeric

    'ready_to_move': ['Yes', 'No', 'NO', np.nan, 'No', np.nan, 'No', 'Yes', 'No', 'Yes'],     # Categorical (Yes/No)

    'Sale_price': [200000, 180000, 215000, 250000, 210000, 190000, 230000, 225000, 220000, 240000]  # Target Variable (Numeric)

}
df=pd.DataFrame(data)
print("orignal data")
print(df)
#impute the dataitems using simple imputer mean,mode,median
df=pd.DataFrame(data)
imputer=SimpleImputer(strategy='mean')
df['square_feet_area']=imputer.fit_transform(df[['square_feet_area']])
df['Year_built']=imputer.fit_transform(df[['Year_built']])
df['over_all_condition']=imputer.fit_transform(df[['over_all_condition']])
#categorical_variable
imputer=SimpleImputer(strategy='most_frequent')
df[['ready_to_move']]=imputer.fit_transform(df[['ready_to_move']])
print("data after imputation")
print(df)