# -*- coding: utf-8 -*-
"""DBSCAN_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0zYYLydgYPV9yLdGEdLvh64PF0rO0Ui
"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
file_path="/content/Wholesale customers data (1).csv"
df=pd.read_csv(file_path)

df

df.info()

#drop channel and region
df.drop(['Channel','Region'],axis=1,inplace=True)

array=df.values
array
df #deleting the chaneel and region from the table

#standard scaler
stscaler = StandardScaler().fit(array)
x= stscaler.transform(array)
x

dbscan=DBSCAN(eps=0.8,min_samples=6)