# -*- coding: utf-8 -*-
"""dt with iris .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137rPs1zvpbCz15ssgwBotxwXFw6EYE2a
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

from google.colab import drive
drive.mount('/content/drive')

file_name = '/content/iris.csv'

import pandas as pd
iris = pd.read_csv(file_name) # Changed 'iris' to 'file_name'
iris.head()

~iris.isnull()

iris.shape

iris.tail()

label_encoder = preprocessing.LabelEncoder()
iris['Species']= label_encoder.fit_transform(iris['Species'])
iris['Species']



