# -*- coding: utf-8 -*-
"""Feature_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDTxkaZWggFiu93yyKrzq_QfR-5sRyRr
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {
    'Age': [25, 30, 35, 40, 45],
    "height": [150, 160, 170, 180, 190],
    "weight" : [50, 60, 70, 80, 90]
}

df = pd.DataFrame(data)
print("original dataframe")
print(df)
scaler = MinMaxScaler()
#normalize the dataset

normalized_data= scaler.fit_transform(df)

normalized_df = pd.DataFrame(normalized_data, columns=df.columns)
print("/nnormalized dataframe (scaled to range [0,1]):")
print(normalized_df)


#standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
standardized_data = scaler.fit_transform(df)
standardized_df = pd.DataFrame(standardized_data, columns=df.columns)
print("/nstandardized dataframe:")
print(standardized_df)

#do the minmax and standization using csv file