# -*- coding: utf-8 -*-
"""multi linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YP7w7vIvupvXW_5BkTODh2P6QRSrkE25
"""

# a large toyota car delership rolled out used cars exchange offer for a new ar. to
# ensure a reasonable profit, the dealer needs to be able to predict the price that the
# dealership will get for used cars
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.regressionplots import influence_plot
import statsmodels.formula.api as smf
import numpy as np

from google.colab import files
uploaded = files.upload()
file_name=list(uploaded.keys())[0]
print(file_name)

df=pd.read_csv(file_name)
df

df.shape

df.corr(numeric_only=True)

#build model
import statsmodels.formula.api as smf


model=smf.ols('MPG~WT+VOL+SP+HP',data=df).fit()

model.params

#add scatter plots for the above code
import matplotlib.pyplot as plt
plt.scatter(df['WT'],df['MPG'])
plt.scatter(df['VOL'],df['MPG'])
plt.scatter(df['SP'],df['MPG'])
plt.scatter(df['HP'],df['MPG'])

#add pair plots for the above code
sns.pairplot(df)

#t and p values
print(model.tvalues,'\n',model.pvalues)

#r squared values
(model.rsquared,model.rsquared_adj)

ml_v=smf.ols("MPG~VOL",data=df).fit()
#t and pvalue
print(ml_w.tvalues,'\n',ml_w.pvalues)

(ml_v.rsquared,ml_v.rsquared_adj)

#only comparing one thing
ml_W=smf.ols("MPG~WT",data=df).fit()
#t and pvalue
print(ml_W.tvalues,'\n',ml_W.pvalues)

(ml_w.rsquared,ml_w.rsquared_adj)

#combination of two things
ml_a=smf.ols("MPG~WT+VOL",data=df).fit()
#t and pvalue
print(ml_w.tvalues,'\n',ml_w.pvalues)

(ml_a.rsquared,ml_a.rsquared_adj)

#combination of three things
ml_a=smf.ols("MPG~WT+VOL+SP+HP",data=df).fit()
#t and pvalue
print(ml_w.tvalues,'\n',ml_w.pvalues)

(ml_a.rsquared,ml_a.rsquared_adj)

