# -*- coding: utf-8 -*-
"""Recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGo6EMS0cV8h56jdpJMmwoMPhmQGTfsB
"""

#cosian, covarience example is youtube

#mount the csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
file_path="/content/Movie.csv"
movies_df=pd.read_csv(file_path)

movies_df

movies_df[0:5]
movies_df['userId']

#number of unique users in the dataset
len(movies_df.userId.unique())

len(movies_df.movie.unique())

user_movie_df=movies_df.pivot(index='userId',
                               columns='movie',
                               values='rating')

user_movie_df

#replace the missing the values
user_movie_df.fillna(0,inplace=True)
user_movie_df

#replacing the missing values with the mean
user_movie_df.mean()

#count of movies who gave rating
user_movie_df.count()

from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

#to know how the spatial distance work lets test with example
from scipy.spatial.distance import correlation
vec1=[5,4,0,0]
vec2=[4,5,3,0]
correlation(vec1,vec2)

user_sim=1-pairwise_distances(user_movie_df.values,metric='cosine')
user_sim

user_sim_df=pd.DataFrame(user_sim)
user_sim_df



