# -*- coding: utf-8 -*-
"""Recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGo6EMS0cV8h56jdpJMmwoMPhmQGTfsB
"""

cosian, covarience example is youtube

#mount the csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
file_path="/content/Movie.csv"
df=pd.read_csv(file_path)

df

