# -*- coding: utf-8 -*-
"""scatter_plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZO8uRvWwxupl0waEzgFtSbOba8CwmKHC
"""

#data preprocessing steps
import statistics
import numpy as np

stock_prices = [100,102,98,105,101,97,99,103,100,98]

variance = statistics.variance(stock_prices)
print(f"Variance of stock prices: {variance}")

numpy_variance = np.var(stock_prices)
print(f"variance of stock prices (using numpy) : {numpy_variance}")

import pandas as pd
import statistics
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    "Day": [1,2,3,4,5,6,7,8,9,10],
    "Stock_A_Returns": [0.02,0.03,-0.01,0.04,-0.03,0.01,0.05,0.02,-0.02,0.01],
    "Stock_B_Returns": [0.01,-0.02,0.04,0.03,0.02,-0.01,0.03,0.04,0.01,0.02]
}
#create a dataframe
df = pd.DataFrame(data)
df
#scatter plot comparing the returns of stock A vs stock B
plt.figure(figsize=(10,6))
plt.scatter(df['Stock_A_Returns'], df['Stock_B_Returns'], color="blue", label="Stock A vs Stock B")

#adding lables and title
plt.xlabel("Stock A Returns")
plt.ylabel("Stock B Returns")
plt.title("Stock Returns Comparison", fontsize=14)
plt.legend()
plt.show()

# pair plot
sns.pairplot(df)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data= {
    "Temperature": [22,55,65,98,42,15,36,45,78,98,66,45,14,7],
    "Humidity": [65,98,14,2,54,15,42,48,75,12,32,42,65,6],
    "wind speed" : [15,32,6,5,4,7,8,5,2,6,2,61,14,13],
    "pressure" : [1015,2302,1548,6547,4521,1452,2366,1547,1042,1025,1023,1564,1254,1425]

}
df=pd.DataFrame(data)
df

#scatter plots : we will get only few features
plt.figure(figsize=(10,6))
plt.scatter(df['Temperature'], df['Humidity'], color="blue", label="temp vs humidity")
plt.scatter(df['Temperature'], df['wind speed'], color="red", label="temp vs wind speed")
plt.scatter(df['Temperature'], df['pressure'], color="green", label="temp vs pressure")

#adding lables and title
plt.xlabel("Temperature")
plt.ylabel("all")
plt.title("Temperature vs Humidity", fontsize=14)
plt.legend()
plt.show()

#pair plot : all the features we will get
sns.pairplot(df)
plt.show()