# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLNtWPnulckoCh63XK0ZuHB4cG8UWLgG
"""

#svm classification
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

filename=r'/content/pima-indians-diabetes.data.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe=pd.read_csv(filename, names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc=SVC()

param_grid={
    'C':[0.1,1,10],
    'kernel':['linear','rbf'],
    'gamma':[0.001,0.01,0.1,1]
}